### ISSUE TITLE
Kotlin Multiplatform

### ISSUE THREAD

**Issue by joreilly** [InkApplications/Shade#63]
### Proposed Change:
Are there any plans to make this a Kotlin Multiplatform library?

**Comment by ReneeVandervelde** [comment]
Yes, It's been on my mind now that multiplatform is becoming more stable. 🙂
This would likely require some breaking changes. So I'll schedule it for a 2.x release.

**Comment by ReneeVandervelde** [comment]
V2 of the SDK was released and supports multiplatform targets :tada:
